### ISSUE TITLE
Video Preprocessing

### ISSUE THREAD

**Issue by Domhnall-Liopa** [Chris10M/Lip2Speech#1]
Hi, 

Nice work!

Could you point me towards the code you use to crop the face and mouth from the LRW samples into the `.npz` files found at `Datasets/SAMPLE_LRW `? I'd like to try it out with my own data

Thanks

**Comment by Chris10M** [comment]
Hello, 

Thank you!. 

To use your own dataset, use the WILD dataloader (We used this train on YouTube videos also). The preprocess.py in datasets/wild/preprocess.py  contains the face detector code and crop mechanism to train for your dataset.
